name: telegram message
on: 
  push:
    branches:
      - master
      - dev
      - jiung
  pull_request:
    branches: 
      - master
      - dev
      - jiung
    
jobs:

  pull_req:
    name: Pull Request msg
    if: contains(github.event_name, 'pull_request')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send git pull req message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO_FIRE }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: | 
          [*] ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}로 Pull Request가 있습니다.
          ${{ github.event.pull_request.user.login }}가 요청했습니다.
          
          
          =*=*=*= Pull Request =*=*=*=
          #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}
          
          ${{ github.event.pull_request.body }}
          =*=*=*=*=*=*= END =*=*=*=*=*=
          
          ${{ github.event.pull_request.html_url }}
          
  pushed:
    name: Push msg
    if: contains(github.event_name, 'push')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send git pushed req message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO_FIRE }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: | 
          [+] 커밋 ${{ github.sha }}(이)가 
          ${{ github.ref }}에 Push 되었습니다.
          ${{ github.event.push.user.login }}(이)가 Push 했습니다.
          
          =/=/=/= Commit Message =/=/=/=
          ${{ github.event.head_commit.message }}
          =/=/=/=/=/=   END   =/=/=/=/=/=
          
          
          ${{ github.event.push.html_url }}
